"""empty message

Revision ID: 3e7c9df63fd0
Revises: 58f8c0073970
Create Date: 2020-11-02 15:35:43.962865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e7c9df63fd0'
down_revision = '58f8c0073970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('answered_today', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'answered_today')
    # ### end Alembic commands ###
