"""empty message

Revision ID: 891a9041591a
Revises: 2864abffd811
Create Date: 2020-11-02 13:16:45.672313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891a9041591a'
down_revision = '2864abffd811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('users', sa.Column('failed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'group_id')
    op.drop_column('users', 'failed')
    op.drop_table('groups')
    # ### end Alembic commands ###
