"""empty message

Revision ID: 94d211cf734b
Revises: e7079819691d
Create Date: 2020-11-02 16:38:12.962086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d211cf734b'
down_revision = 'e7079819691d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('color', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'color')
    # ### end Alembic commands ###
